### ISSUE TITLE
How to use and deploy on Phoenix

### ISSUE THREAD

**Issue by jamilabreu** [edgedb/edgedb-elixir#19]
@nsidnev Moving the conversation here 😄 

Let's use this issue to discuss adding examples for how to use and deploy on Phoenix. Excited!

**Comment by nsidnev** [comment]
@jamilabreu I created a repo that shows how to use this driver with Phoenix. Of course, right now this is a very simple example, but I think it can be considered a starting point :)

https://github.com/nsidnev/phoenix-edgedb-example

**Comment by jamilabreu** [comment]
@nsidnev Awesome! It works and is definitely a solid starting point. Have you tried to deploy anywhere yet?

**Comment by nsidnev** [comment]
No, I haven't done that yet and I don't think I'll create a real deployment, since that would require an EdgeDB instance setup along with Elixir web service and server maintenance. But I will try to create a step-by-step guide on how to do this and add it to the example repository.

**Comment by nsidnev** [comment]
I'm closing this issue because the example is already running on fly.io and it seems to work. If you have more questions, reopen the issue or create a new one in the example repository.
